version: 1.0.{build}

image: Visual Studio 2022

branches:
  only:
    - main

configuration: Release

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1

install:
  - dotnet --info

before_build:
  - dotnet restore MacroKeyboardSync\MacroKeyboardSync.sln

build_script:
  - dotnet build MacroKeyboardSync\MacroKeyboardSync.sln -c %CONFIGURATION% --no-restore
  - dotnet publish MacroKeyboardSync\MacroKeyboardSync.csproj -c %CONFIGURATION% --no-restore -o publish\MacroKeyboardSync
  - 7z a MacroKeyboardSync.zip .\publish\MacroKeyboardSync\*
  - 7z a MacroKeyboardPico.zip .\src\*

# Keine Unit-Tests vorhanden
test: off

artifacts:
  - path: MacroKeyboardSync.zip
    name: MacroKeyboardSync
  - path: MacroKeyboardPico.zip
    name: MacroKeyboardPico
